### PR TITLE
[#166787075] Added alert and locales

### PR DESCRIPTION
**Pull request by matgentili**
Added alert and locales

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#166787075](https://www.pivotaltracker.com/story/show/166787075): Come CIT quando clicco su "PIN dimenticato" voglio avere un alert che mi dice quello che sta per succedere

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by matgentili** [comment]
@matteodesanti What do you think about the name of the alert title ?

ita


eng

**Comment by matteodesanti** [comment]
perfect!

**Comment by matteodesanti** [comment]
Sorry @matgentili can you avoid the red color in the confirm button?

**Comment by matgentili** [comment]
@matteodesanti  Sorry I didn't notice, I immediately invert the colors!

**Comment by matgentili** [comment]
@matteodesanti Done.
color button

I noticed that even in the profile when you want to reset the pin an alert comes out with the red confirmation button, is it correct here?

**Pull request merged**
