### PR TITLE
[#169807667] Fixed tabs services home

### PR DESCRIPTION
**Pull request by Alex193a**
Reverted the change in ServicesHomeScreen of the PR #1409.

**BEFORE:**

**NOW:**

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🐞 [#169807667](https://www.pivotaltracker.com/story/show/169807667): Fix tab home servizi

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Alex193a** [comment]
@Undermaken I had not considered this solution since the idea of the previous PR was to extrapolate the tabs completely from the screen.
I think it is a good solution, indeed it seems even more reactive than before the transition from one tab to another!!
I will do some more tests and then I'll proceed with the commit.

**Comment by Alex193a** [comment]
@Undermaken I had not considered this solution since the idea of the previous PR was to extrapolate the tabs completely from the screen.
I think it is a good solution, indeed it seems even more reactive than it was before (with the tab rendering in ServicesTab) during the switch from one tab to another!!
I will do some more tests and then I'll proceed with the commit.

**Comment by Undermaken** [comment]
> @Undermaken I had not considered this solution since the idea of the previous PR was to extrapolate the tabs completely from the screen.
> I think it is a good solution, indeed it seems even more reactive than it was before (with the tab rendering in ServicesTab) during the switch from one tab to another!!
> I will do some more tests and then I'll proceed with the commit.

thank you @Alex193a

**Pull request merged**
