### PR TITLE
[#165306971] Remove unused fonts

### PR DESCRIPTION
**Pull request by valentinacala**
This pr is aimed to:
1. make the app use only the io-font-icons (somewhere other icon libraries were used yet)
2. remove all the references to unused fonts into the app and make only useful fonts been linked.

To solve point 2, it is proposed to use the library **react-native-asset** (reference here: https://github.com/unimonkiez/react-native-asset). Not being required at runitime, it is proposed to install it globally when to update or add a content

Some considerations bringing to the proposed solution:
- "react-native link" will be soon deprecated (it will require to specify the library to link)
- "react-native link react-native-vector-icons" can't be customized to avoid it links all the available fonts in the library. 
- Even if the documentation suggests to use "react-native link react-native-vector-icons" to use custom fonts, it doesn't link custom asset (here the documentation: https://www.reactnative.guide/12-svg-icons-using-react-native-vector-icons/12.1-creating-custom-iconset.html)
- react-native link will be implemented to support the link of assets but it was not released yet

The following content reports some pieces of evidence experienced on the app. In particular, looking at the fonts.ts definitions, it seems that not all the TitilliumWeb fonts imported as a custom asset are or will be used.

----------
**DETAILS ON POINT 2**
The following react-native-vector-icons font are maintained for both iOS and Android:
- **Ionicons font**: if removed, the native base CheckBox is not properly rendered.
On iOS: immagine <--> immagine
On Android:immagine <--> immagine

- **RobotoMono-Regular** font: used for the masked part of the card pan
- **io-font-icon** 

What concerns **TitilliumWeb** font both iOS and Android require:
 - TitilliumWeb-Bold
- TitilliumWeb-SemiBold
- TitilliumWeb-Light (it's not yet used into the application but it is declared on ts/theme/fonts.ts) 
If they are removed, the corresponding fontweight is not applied. Here an example on bolded text: immagineimmagine

What concerns the other fonts of the TitilliumWeb family, both the operating system doesn't require the following fonts:
- TitilliumWeb-Italic
- TitilliumWeb-SemiBoldItalic
- TitilliumWeb-LightItalic
- TitilliumWeb-Black
- TitilliumWeb-ExtraLight
- TitilliumWeb-ExtraLightItalic
- TitilliumWeb-BoldItalic (a text can't be both bold and italic: if both the attributes are applied on a text item, it take only the last declared style)

**iOS only** 
iOS doesn't require also the following fonts of the TitilliumWeb family (so they had been removed from the Info.plist file):
- TitilliumWeb-Regular
- TitilliumWeb-RegularItalic

What concerns the italic font on iOS, if the italic attribute is applied to a plain text, the page results the same if they are included or not in the ios/ItaliaApp/Info.plist file : 
immagine

**Android only**
Android requires the following fonts of the TitilliuWeb family to be declared (the corresponding .ttf file has to be stored under android/app/src/main/assets/fonts even if .ttf files are stored under the project asset/fonts folders):
- TitilliumWeb-Regular (if removed, any text item assumes the custom font of the device)
- TitilliumWeb-RegularItalic (if removed, any text item with the italic attribute assumes the custom font of the device): 
immagine

--------------
**DETAILS ON POINT 1**

Here the final result where they had been inserted the io-font-icons:
- the icon in the myddle of the qrcode scanner (as displayed in the comment to the code)
- the icon in the "add memo" button: 
immagine and  immagine

- The alert icon near "importo": 
immagine

- the cross in the search bar of the message home screen: 
immagine

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a description of your PR changes.
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🌟 [#165306971](https://www.pivotaltracker.com/story/show/165306971): Rimuovere tutti i font non utilizzati

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by valentinacala** [comment]
Looking on the font usages, I'm finding some cases where they are used icon fonts different to the io-icon-font. It occurs for example on the qr code scanner:

immagine

immagine

It is preferred to mantain the used icon or to use the io-icon-font icons?
cc @matteodesanti

**Comment by matteodesanti** [comment]
Tks @valentinacala : using the io-icon-font icons is a perfect solution!

**Comment by fpersico** [comment]
@valentinacala 

1) Regarding the TitilliumWeb font we must include all the "variations" we support in the `fonts.ts`
2) Regarding the PR you have correctly **removed** the unused fonts but you are not preventing the fonts to be **added again** on next "react-native link". Read the documentation to check how to properly include only the selected fonts on link.

**Comment by valentinacala** [comment]
@cloudify @fpersico  I can't access the security/snyk error report. Can you help me to access the report?

**Pull request merged**
