### PR TITLE
[#164896228] Message list rows predictable and fixed height

### PR DESCRIPTION
**Pull request by lmorelli986**
This PR aims to change message list components setting their height fixed letting list height to be predictable and the pre-calculated for optimization pourposes.

Simulator Screen Shot - iPhone X - 2019-05-10 at 14 42 43

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  @types dependencies were added to package.json, as a dependency for others.<br/><i>You need to move &#64;types/memoize-one into "devDependencies"?</i>
  </td>
    </tr>
  </tbody>
</table>




## Affected stories

  * 🌟 [#164896228](https://www.pivotaltracker.com/story/show/164896228): Le righe della lista messaggi devono avere un altezza fissa o prevedibile


New dependencies added: <a href='https://www.npmjs.com/package/@types/memoize-one'><code>&#64;types/memoize-one</code></a> and <a href='https://www.npmjs.com/package/memoize-one'><code>memoize-one</code></a>.


<h2><a href="http://npmjs.com/package/@types/memoize-one">&#64;types/memoize-one</a></h2>
<p>Author: Unknown</p>
<p>Description: TypeScript definitions for memoize-one</p>
<p>Homepage: <a href="http://npmjs.com/package/@types/memoize-one">http://npmjs.com/package/@types/memoize-one</a></p>

<table>
  <thead><tr><th></th><th width="100%"></th></tr></thead>
  <tr><td>Created</td><td>12 months ago</td></tr><tr><td>Last Updated</td><td>about 1 month ago</td></tr><tr><td>License</td><td>MIT</td></tr><tr><td>Maintainers</td><td>1</td></tr><tr><td>Releases</td><td>5</td></tr><tr><td>Direct Dependencies</td><td></td></tr>
</table>

<details>
<summary><code>README</code></summary></br>

# Installation
> `npm install --save @types/memoize-one`

# Summary
This package contains type definitions for memoize-one ( https://github.com/alexreardon/memoize-one#readme ).

# Details
Files were exported from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/memoize-one

Additional Details
 * Last updated: Tue, 12 Mar 2019 23:39:43 GMT
 * Dependencies: none
 * Global values: none

# Credits
These definitions were written by Karol Majewski <https://github.com/karol-majewski>, Frank Li <https://github.com/franklixuefei>.


</details>




<h2><a href="https://github.com/alexreardon/memoize-one#readme">memoize-one</a></h2>
<p>Author: Alex Reardon</p>
<p>Description: A memoization library which only remembers the latest invocation</p>
<p>Homepage: <a href="https://github.com/alexreardon/memoize-one#readme">https://github.com/alexreardon/memoize-one#readme</a></p>

<table>
  <thead><tr><th></th><th width="100%"></th></tr></thead>
  <tr><td>Created</td><td>over 2 years ago</td></tr><tr><td>Last Updated</td><td>about 1 month ago</td></tr><tr><td>License</td><td>MIT</td></tr><tr><td>Maintainers</td><td>1</td></tr><tr><td>Releases</td><td>22</td></tr><tr><td>Direct Dependencies</td><td></td></tr><tr><td>Keywords</td><td>memoize, memoization, cache and performance</td></tr>
</table>

<details>
<summary><code>README</code></summary></br>

# memoize-one

A memoization library that only caches the result of the most recent arguments.

[Build Status](https://travis-ci.org/alexreardon/memoize-one)
[npm](https://www.npmjs.com/package/memoize-one)
[dependencies](https://david-dm.org/alexreardon/memoize-one)
[Downloads per month](https://www.npmjs.com/package/memoize-one)
[min](https://www.npmjs.com/package/memoize-one)
[minzip](https://www.npmjs.com/package/memoize-one)

## Rationale

Unlike other memoization libraries, `memoize-one` only remembers the latest arguments and result. No need to worry about cache busting mechanisms such as `maxAge`, `maxSize`, `exclusions` and so on which can be prone to memory leaks. `memoize-one` simply remembers the last arguments, and if the function is next called with the same arguments then it returns the previous result.

## Usage

### Standard usage

```js
import memoizeOne from 'memoize-one';

const add = (a, b) => a + b;
const memoizedAdd = memoizeOne(add);

memoizedAdd(1, 2); // 3

memoizedAdd(1, 2); // 3
// Add function is not executed: previous result is returned

memoizedAdd(2, 3); // 5
// Add function is called to get new value

memoizedAdd(2, 3); // 5
// Add function is not executed: previous result is returned

memoizedAdd(1, 2); // 3
// Add function is called to get new value.
// While this was previously cached,
// it is not the latest so the cached result is lost
```

## Installation

```bash
# yarn
yarn add memoize-one

# npm
npm install memoize-one --save
```

## Module usage

### ES6 module

```js
import memoizeOne from 'memoize-one';
```

### CommonJS

If you are in a CommonJS environment (eg [Node](https://nodejs.org)), then **you will need to add `.default` to your import**:

```js
const memoizeOne = require('memoize-one').default;
```

## Custom equality function

You can also pass in a custom function for checking the equality of two sets of arguments

```js
const memoized = memoizeOne(fn, isEqual);
type EqualityFn = (newArgs: mixed[], oldArgs: mixed[]) => boolean;
```

An equality function should return `true` if the arguments are equal. If `true` is returned then the wrapped function will not be called.

The default equality function is a shallow equal check of all arguments (each argument is compared with `===`). If the `length` of arguments change, then the default equality function makes no shallow equality checks. You are welcome to decide if you want to return `false` if the `length` of the arguments is not equal

```js
const simpleIsEqual: EqualityFn = (
  newArgs: mixed[],
  lastArgs: mixed[],
): boolean =>
  newArgs.length === lastArgs.length &&
  newArgs.every(
    (newArg: mixed, index: number): boolean =>
      shallowEqual(newArg, lastArgs[index]),
  );
```

A custom equality function needs to compare `Arrays`. The `newArgs` array will be a new reference every time so a simple `newArgs === lastArgs` will always return `false`.

Equality functions are not called if the `this` context of the function has changed (see below).

Here is an example that uses a `lodash.isequal` deep equal equality check

> `lodash.isequal` correctly handles deep comparing two arrays

```js
import memoizeOne from 'memoize-one';
import isDeepEqual from 'lodash.isequal';

const identity = x => x;

const shallowMemoized = memoizeOne(identity);
const deepMemoized = memoizeOne(identity, isDeepEqual);

const result1 = shallowMemoized({ foo: 'bar' });
const result2 = shallowMemoized({ foo: 'bar' });

result1 === result2; // false - difference reference

const result3 = deepMemoized({ foo: 'bar' });
const result4 = deepMemoized({ foo: 'bar' });

result3 === result4; // true - arguments are deep equal
```

## `this`

### `memoize-one` correctly respects `this` control

This library takes special care to maintain, and allow control over the the `this` context for **both** the original function being memoized as well as the returned memoized function. Both the original function and the memoized function's `this` context respect [all the `this` controlling techniques](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md):

- new bindings (`new`)
- explicit binding (`call`, `apply`, `bind`);
- implicit binding (call site: `obj.foo()`);
- default binding (`window` or `undefined` in `strict mode`);
- fat arrow binding (binding to lexical `this`)
- ignored this (pass `null` as `this` to explicit binding)

### Changes to `this` is considered an argument change

Changes to the running context (`this`) of a function can result in the function returning a different value even though its arguments have stayed the same:

```js
function getA() {
  return this.a;
}

const temp1 = {
  a: 20,
};
const temp2 = {
  a: 30,
};

getA.call(temp1); // 20
getA.call(temp2); // 30
```

Therefore, in order to prevent against unexpected results, `memoize-one` takes into account the current execution context (`this`) of the memoized function. If `this` is different to the previous invocation then it is considered a change in argument. [further discussion](https://github.com/alexreardon/memoize-one/issues/3).

Generally this will be of no impact if you are not explicity controlling the `this` context of functions you want to memoize with [explicit binding](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md#explicit-binding) or [implicit binding](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md#implicit-binding). `memoize-One` will detect when you are manipulating `this` and will then consider the `this` context as an argument. If `this` changes, it will re-execute the original function even if the arguments have not changed.

## When your result function `throw`s

> There is no caching when your result function throws

If your result function `throw`s then the memoized function will also throw. The throw will not break the memoized functions existing argument cache. It means the memoized function will pretend like it was never called with arguments that made it `throw`.

```js
const canThrow = (name: string) => {
  console.log('called');
  if (name === 'throw') {
    throw new Error(name);
  }
  return { name };
};

const memoized = memoizeOne(canThrow);

const value1 = memoized('Alex');
// console.log => 'called'
const value2 = memoized('Alex');
// result function not called

console.log(value1 === value2);
// console.log => true

try {
  memoized('throw');
  // console.log => 'called'
} catch (e) {
  firstError = e;
}

try {
  memoized('throw');
  // console.log => 'called'
  // the result function was called again even though it was called twice
  // with the 'throw' string
} catch (e) {
  secondError = e;
}

console.log(firstError !== secondError);

const value3 = memoized('Alex');
// result function not called as the original memoization cache has not been busted
console.log(value1 === value3);
// console.log => true
```

## Performance :rocket:

### Tiny

`memoize-one` is super lightweight at [min](https://www.npmjs.com/package/memoize-one) minified and [minzip](https://www.npmjs.com/package/memoize-one) gzipped. (`1KB` = `1,024 Bytes`)

### Extremely fast

`memoize-one` performs better or on par with than other popular memoization libraries for the purpose of remembering the latest invocation.

**Results**

- [simple arguments](https://www.measurethat.net/Benchmarks/ShowResult/4452)
- [complex arguments](https://www.measurethat.net/Benchmarks/ShowResult/4488)

The comparisons are not exhaustive and are primarily to show that `memoize-one` accomplishes remembering the latest invocation really fast. The benchmarks do not take into account the differences in feature sets, library sizes, parse time, and so on.

## Code health :thumbsup:

- Tested with all built in [JavaScript types](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch1.md).
- 100% code coverage
- [Continuous integration](https://travis-ci.org/alexreardon/memoize-one) to run tests and type checks.
- [`Flow` types](http://flowtype.org) for safer internal execution and external consumption. Also allows for editor autocompletion.
- Follows [Semantic versioning (2.0)](http://semver.org/) for safer consumption.
- No dependencies


</details>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 02b637d5421567060508a1d9179f55d60fd40809 into 468c89c9738ea6df912efeda691e52b856a7b1b9 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-40c248496f38c5a69464554ea1871ef2610f1223)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by lmorelli986** [comment]
@cloudify I got forbidden access to https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-40c248496f38c5a69464554ea1871ef2610f1223

I just removed an unncecessary dependency, was it related to the issue you told me about?

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 38c94ac49d8414a2d5be0fbff9e6c8eb460e5832 into 468c89c9738ea6df912efeda691e52b856a7b1b9 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-b792473db19e48dd70b8343ce007dbdfa34bf186)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging ebfdd26ca42aab7166c889daa21895aec3780eee into 468c89c9738ea6df912efeda691e52b856a7b1b9 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-da527a44de21233eb0561e9f1ff4732ad095b456)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 156fb5ae209faae7164617420003214d7e43fd7c into b04228a9804164d6b7b8deecbb980b9243504a7c - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-401328d3aff812af6f4020b9abfb1882739e4a83)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 13638905195859958e70ec8dd7fb0f13e79447e7 into b04228a9804164d6b7b8deecbb980b9243504a7c - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-367b848f1e68797898a3a5da6728dd909cd05b3e)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging b3bfa671064dd822cc0c4ff0ceef8f3989da75b9 into c6fbdd8755ec9ea0b801c7fdac71252f8a510964 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-893e22730c0925c29c72391cb76f2747aa5145c6)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 85cbb89e0c00797f78471c36ad44298abbfc98cb into c6fbdd8755ec9ea0b801c7fdac71252f8a510964 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-d83ae0582318ea32e07f3fd085a07f57235b7e97)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 1 alert** when merging 50c9c0f54f14ffd696334a270d8bd767f7cc1dbb into c6fbdd8755ec9ea0b801c7fdac71252f8a510964 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-3e7fac6777858720adb07e941b9a053978e812e4)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
