### PR TITLE
[#164427415] Add animated loader to MessageListItem

### PR DESCRIPTION
**Pull request by fpersico**
Loading

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#164427415](https://www.pivotaltracker.com/story/show/164427415): Quando un messaggio si sta caricando va visualizzato un placeholder animato


New dependencies added: <a href='https://www.npmjs.com/package/rn-placeholder'><code>rn-placeholder</code></a>.


<h2><a href="https://github.com/mfrachet/rn-placeholder">rn-placeholder</a></h2>
<p>Author: Marvin FRACHET</p>
<p>Description: Display some placeholder stuff before rendering your text or media content in React Native</p>
<p>Homepage: <a href="https://github.com/mfrachet/rn-placeholder">https://github.com/mfrachet/rn-placeholder</a></p>

<table>
  <thead><tr><th></th><th width="100%"></th></tr></thead>
  <tr><td>Created</td><td>almost 2 years ago</td></tr><tr><td>Last Updated</td><td>2 months ago</td></tr><tr><td>License</td><td>MIT</td></tr><tr><td>Maintainers</td><td>1</td></tr><tr><td>Releases</td><td>15</td></tr><tr><td>Direct Dependencies</td><td><a href='https://www.npmjs.com/package/prop-types'><code>prop-types</code></a></td></tr><tr><td>Keywords</td><td>react-native, ios, android and expo</td></tr>
</table>

<details>
<summary><code>README</code></summary></br>

[Build Status](https://travis-ci.org/mfrachet/rn-placeholder)
[Coverage Status](https://coveralls.io/github/mfrachet/rn-placeholder?branch=master)
[License: MIT](https://opensource.org/licenses/MIT)

Display some placeholder stuff before rendering your text or media content in React Native.

\_Fully compatible with [Expo](https://expo.io/) and [react-native-web](https://github.com/necolas/react-native-web).

_New documentation available [mfrachet.github.io/rn-placeholder](https://mfrachet.github.io/rn-placeholder/)_

---

<p align="center">

</p>

---

# Content

- <a href="#usage">How to use it ?</a>
- [Components available](./API.md)
- [Creating a custom component](./API.md#custom)
- [Using default animations](./ANIMATIONS.md#default)
- [Using a custom animation](./ANIMATIONS.md#custom)

<h1 name="#usage">Usage</h1>

### Installation

```javascript
$ npm install rn-placeholder --save
```

### In your code

```javascript
import Placeholder from 'rn-placeholder';

/*...*/
render() {
    return (
      <View>
        <Placeholder.ImageContent
          size={60}
          animate="fade"
          lineNumber={4}
          lineSpacing={5}
          lastLineWidth="30%"
          onReady={this.state.isReady}
        >
          <Text>Placeholder has finished :D</Text>
        </Placeholder.ImageContent>
      </View>
    );
  }
/*...*/
```

When the value of `this.state.isReady` changes to something _existing_, the `<Text>` component will be rendered


</details>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
can we add it also for the service name? (perhaps in a different PR)

**Comment by fpersico** [comment]
@cloudify service name animated loaded added

Loading

**Comment by cloudify** [comment]
lovely, thanks

**Pull request merged**
