### PR TITLE
[#166157108] Change PagoPA logo according to environment in wallet section

### PR DESCRIPTION
**Pull request by laurapugliese**
Change PagoPA logo according to environment in wallet section

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a description of your PR changes.
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🐞 [#166157108](https://www.pivotaltracker.com/story/show/166157108): In tutta la sezione Wallet il logo di PagoPA nell'header deve differenziarsi in base all'ambiente

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by laurapugliese** [comment]
This PR aims to fix the pagopa logo that must be differentiated according to the environment of the test or production in the whole Wallet section (where present).

Screenshot_20190524-143207
Screenshot_20190524-143214
Screenshot_20190524-143217

**Comment by fpersico** [comment]
@laurapugliese Instead of connecting the whole WalletLayout to the store what you think about creating a PagoPALogo component that is connected to the store? In this way only this component and not the whole layout is rerendered when the isDebugEnabled var in the store is changed.

**Comment by laurapugliese** [comment]
> @laurapugliese Instead of connecting the whole WalletLayout to the store what you think about creating a PagoPALogo component that is connected to the store? In this way only this component and not the whole layout is rerendered when the isDebugEnabled var in the store is changed.

good! yes i think it's better! I proceed with the changes 👍

**Pull request merged**
