### PR TITLE
[#165854051] Added buttons for favorites and contextual menu in the detail of card transactions

### PR DESCRIPTION
**Pull request by laurapugliese**
cancellation of the card is not allowed for the moment

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#165854051](https://www.pivotaltracker.com/story/show/165854051): Come CIT voglio vedere il menu contestuale e la stellina per aggiungere ai preferiti anche nel dettaglio del metodo di pagamento.

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by laurapugliese** [comment]
In this PR the contextual menu has been added and the star in the transaction details of that card. @cloudify @fpersico For the moment I have not inserted the possibility to remove the card inside the detail. Is it correct or should I add this possibility as well? thanks

detail_transactions

**Comment by fpersico** [comment]
> In this PR the contextual menu and the star has been added in the transaction details of that card. @cloudify @fpersico For the moment I have not inserted the possibility to remove the card inside the detail. Is it correct or should I add this possibility as well? thanks
> 
> detail_transactions

@matteodesanti please check the question above.

**Comment by matteodesanti** [comment]
Tks for the question @laurapugliese. I suggest to leave the delete function inside the menu in the single-method view aswell..  If the user delete the method, he should be redirected to the method general list.

**Comment by laurapugliese** [comment]
> Tks for the question @laurapugliese. I suggest to leave the delete function inside the menu in the single-method view aswell.. If the user delete the method, he should be redirected to the method general list.

@matteodesanti as suggested, in the commit 55a854b I added the option to remove the card to the context menu (@fpersico for cc):

delete_option

**Pull request merged**
