### PR TITLE
[#165913421] Fix pinpad UI on small screen

### PR DESCRIPTION
**Pull request by Edigio**
Fix pinpad UI on small screen

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🐞 [#165913421](https://www.pivotaltracker.com/story/show/165913421): Come CIT voglio vedere un pinpad compatibile anche con gli schermi più piccoli.

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Edigio** [comment]
**iPhone X:** with FaceID
iphonex_faceid

**iPhone 6** with TouchID
iphone6_touchid

**Android nokia 7 plus** with Finger Print
nokia_android

**Comment by Edigio** [comment]
@matteodesanti i think that to center vertically all the elements in the main container is the best solution. I work there and then i post a screen with the result

**Comment by Edigio** [comment]
Before and after on iPhoneX. @matteodesanti what do you think about it?

primadopo

**Comment by matteodesanti** [comment]
Ok!!!

**Comment by matteodesanti** [comment]
Sorry, have you tested it on iPhone SE?

**Comment by Edigio** [comment]
yes, but just now for a best result i have added a little fix to reduce the space between the label 'Did you forget the pin' and the pinpad. I think it's a good UI now

**iPhone X**
Simulator Screen Shot - iPhone X - 2019-06-06 at 09 09 09

**iPhone SE**
Simulator Screen Shot - iPhone SE - 2019-06-06 at 09 09 11

**Comment by fpersico** [comment]
@matteodesanti please approve if it is ok to merge.

**Comment by matteodesanti** [comment]
@Edigio can you reduce the distance between the label "use the fingerprint or enter the pin" and the input field? Th goal is to obtain, on iphone SE, at leat 32px of bottom padding (40px better).

**Comment by Edigio** [comment]
> @Edigio can you reduce the distance between the label "use the fingerprint or enter the pin" and the input field? Th goal is to obtain, on iphone SE, at leat 32px of bottom padding (40px better).

I have reduced the spaces between the components and now the bottom padding is ~ 40 px on iPhone SE
Senzanome

**Pull request merged**
