### PR TITLE
[#159068543] Optimize Android binary with Proguard (fixed)

### PR DESCRIPTION
**Pull request by Alex193a**
Fixed the release build with Proguard enabled. The generated APK works correctly so the .aab file is also supposed to work correctly.

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#159068543](https://www.pivotaltracker.com/story/show/159068543): Ottimizzare binario Android con Proguard

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by fpersico** [comment]
@Alex193a can you write here the size of the APK WITH and WITHOUT Proguard?

**Comment by Alex193a** [comment]
@fpersico sure!

- without Proguard: 37,4MB (37.380.913 bytes)
- with Proguard 35,5MB (35.503.864 bytes)

**Comment by Alex193a** [comment]
@fpersico with the commit [617788c](https://github.com/teamdigitale/io-app/pull/1036/commits/617788c3f62097f161afd73584d872f83ecc1155) I've removed the unnecessary "@Keep" annotation in the MainApplication class and everything seems to work correctly.

**Pull request merged**
