### PR TITLE
[#166761503] Added modal view wallet info

### PR DESCRIPTION
**Pull request by matgentili**
Added the help modal for the wallet tab

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#166761503](https://www.pivotaltracker.com/story/show/166761503): Come Cit voglio un punto interrogativo nello screen del wallet

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by matgentili** [comment]
ITA:

ita

ENG:

eng

**Comment by matgentili** [comment]
In these screenshots the title is hidden to show the body.
ITA:
ita


ENG:
eng

**Comment by Undermaken** [comment]
@matgentili Is it still in draft or it can be review?

**Pull request merged**
