### PR TITLE
TSLint shared rules

### PR DESCRIPTION
**Pull request by cloudify**
Migrating all our tslint rules to `italia-tslint-rules` with the objective to share the same rules across all projects.

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a Pivotal story at the beginning of the PR title (see below).
  </td>
    </tr>
  </tbody>
</table>



  Example of PR titles that include pivotal stories:

  * single story: `[#123456] my PR title`
  * multiple stories: `[#123456,#123457,#123458] my PR title`

    
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
This pull request **introduces 4 alerts** when merging 758bf95139c727336eaf0eb954876459d554424e into 255e3a84823c688960faf5b82984b1d9de1a6e1c - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-0a9a234e50d9b8125ae83908d42ee61f87133210)

**new alerts:**

* 4 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 4 alerts** when merging bcc84951cd8cececc41cb7994b8d2753d425597e into a10c70efdbad5d90bbaf29c318a05c792f1ce16b - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-15e79fcbe3668f76c63512e01c5f220572200f03)

**new alerts:**

* 4 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 4 alerts** when merging 0a9878a9eb9119f2911cba4fe10a5b7e125dc9cd into e40b91531873ca8fa6a469033c348ac8823b5b80 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-d8ad3bcdbd75977ae76dfc44e1e6679e0dcafc15)

**new alerts:**

* 4 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cloudify** [comment]
This pull request **introduces 4 alerts** when merging 0a0b305d415b8e0de13d61e83e0977f9b60d060b into e40b91531873ca8fa6a469033c348ac8823b5b80 - [view on LGTM.com](https://lgtm.com/projects/g/teamdigitale/io-app/rev/pr-da039fca2282650a537e3ca6c98514828be23314)

**new alerts:**

* 4 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
