### PR TITLE
[#157769361] delete unused styles and other fixes on styles

### PR DESCRIPTION
**Pull request by valentinacala**
This pr removes the unused styles and fix some aspects on styles as:
* import style classes inside the component/screen using them instead of using the imported files wallet.ts, style.ts, PinPad.style.ts, CardComponent.style.ts

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#165306971](https://www.pivotaltracker.com/story/show/165306971): Rimuovere tutti i font non utilizzati

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
@fpersico please review

**Comment by fpersico** [comment]
@valentinacala please resolve conflicts.

**Comment by valentinacala** [comment]
I've done something wrong on solving conflicts on merge. I created a new branch from the last correct commit and close this one. Here the new pr: https://github.com/teamdigitale/io-app/pull/1028

**Pull request closed without merging**
