### PR TITLE
[#165214561] Make idp selection screen top header smaller and slidable 

### PR DESCRIPTION
**Pull request by lmorelli986**
This PR aims to remove subtitle and make title slidable in idp selection screen.

iPhone 5s screen:
screen

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🐞 [#165214561](https://www.pivotaltracker.com/story/show/165214561): lo screen per scelta dell’idp deve scrollare tutto, anche la parte della testata, non solo la sezione con i pulsanti dei vari idp

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by fpersico** [comment]
@lmorelli986 The "bounce/scroll to refresh" effect is really strange.
@cloudify What you think?

**Comment by cloudify** [comment]
I don't like it at all! at least the top overlay should be white. We should also remove all that padding before the logos, it's a waste of space. Also not sure about the `Cancel` button, does it just to a back? if that's the case we can get rid of it.

**Comment by lmorelli986** [comment]
@cloudify yes, it does the same as pressing the top left back button

**Comment by cloudify** [comment]
@matteodesanti what do you think?

**Comment by cloudify** [comment]
We need to:

* white background for whole screen (content)
* grey background for IdP buttons 
* possibly use smaller tag for title
* make vertical padding equal to horizontal padding

**Comment by lmorelli986** [comment]
Fixed:   
✅ white background for whole screen (content)
✅grey background for IdP buttons
✅make vertical padding equal to horizontal padding

Still missing: 

* possibly use smaller tag for title

**Comment by cloudify** [comment]
Thanks @lmorelli986 pls post a screenshot as soon as you're done

**Comment by lmorelli986** [comment]
I've finished all bulletpoints but I'm still unsatisfied by Continue button. I'd get rid of it.

iPhone 5s
Simulator Screen Shot - iPhone 5s - 2019-04-17 at 12 21 56
iPhone X
Simulator Screen Shot - iPhone X - 2019-04-17 at 12 23 11

**Comment by cloudify** [comment]
LGTM, @matteodesanti pls refiew

**Pull request merged**
