### PR TITLE
[#165716236] Fixed sticky header in services list

### PR DESCRIPTION
**Pull request by Alex193a**
Fixed the the graphic bug introduced in the services list (old) by the PR #1247.

**BEFORE:**

**AFTER:**

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#165716236](https://www.pivotaltracker.com/story/show/165716236): Come CIT voglio vedere il componente SectionHeader ancorato in alto subito sotto la header quando lo screen scrolla

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by francescopersico** [comment]
@Undermaken the After image seem not using sticky headers.

**Comment by Alex193a** [comment]
Yes, there is no sticky header in the old service list.  From what I remember it was only foreseen in the new one.

**Comment by Undermaken** [comment]
@francescopersico Yes I think the same as @Alex193a said.
Since we are replacing the service list, the sticky headers should be available only for the new list.
Anyway @matteodesanti can confirm.

**Pull request merged**
